version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  test:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run: npm install
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run: npm run audit

workflows:
  build_test_analyze:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
